from fastapi import APIRouter, HTTPException
from fastapi.responses import StreamingResponse
from openai import AuthenticationError, RateLimitError
from app.services.ai_service import chat, chat_stream
from app.models.schemas import ChatRequest, ChatResponse
from app.services.rate_limiter import is_rate_limited

router = APIRouter(prefix="/chat", tags=["chat"])


@router.post("/", response_model=ChatResponse)
async def chat_endpoint(req: ChatRequest):
    """
    Ask anything about an Indian stock.

    Example body:
    {
      "message": "Why did Zomato fall last week?",
      "symbol": "ZOMATO",
      "user_id": "user_123",
      "plan": "pro"
    }
    """
    # Enforce daily query limit check
    if await is_rate_limited(req.user_id, req.plan):
        raise HTTPException(
            status_code=429,
            detail=f"Daily query limit reached. Your plan ({req.plan.capitalize()}) is limited. Please upgrade for more capacity."
        )

    try:
        return await chat(
            message=req.message,
            symbol=req.symbol,
            user_id=req.user_id,
            plan=req.plan,
        )
    except AuthenticationError:
        raise HTTPException(
            status_code=401,
            detail="OpenAI API key is invalid. Check OPENAI_API_KEY in .env.",
        )
    except RateLimitError:
        raise HTTPException(
            status_code=402,
            detail="OpenAI quota exceeded. Add billing/credits or use a different API key.",
        )
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))


@router.post("/stream")
async def chat_stream_endpoint(req: ChatRequest):
    """
    Streaming version — sends text as it's generated by Claude/GPT.
    Ideal for the chat UI so users see a response immediately.
    """
    # Enforce daily query limit check
    if await is_rate_limited(req.user_id, req.plan):
        raise HTTPException(
            status_code=429,
            detail=f"Daily query limit reached. Your plan ({req.plan.capitalize()}) is limited. Please upgrade for more capacity."
        )

    async def generate():
        try:
            async for chunk in chat_stream(req.message, req.symbol):
                yield chunk
        except AuthenticationError:
            yield "\n[Error: OpenAI API key is invalid. Check OPENAI_API_KEY in .env.]"
        except RateLimitError:
            yield "\n[Error: OpenAI quota exceeded. Add billing/credits or use a different API key.]"
        except Exception as e:
            yield f"\n[Error: {e}]"

    return StreamingResponse(generate(), media_type="text/plain")

